### ISSUE TITLE
y=(x + rannor(2315)*0.2 > 0.35 )

### ISSUE THREAD

**Issue by ydd623922941** [xieliaing/SAS#13]
hi 
 i have a small question in your AUC file.
y=(x + rannor(2315)*0.2 > 0.35 )

why is rannor(2315) rather than other number and >0.35 ??

thanks!

**Comment by robsannaa** [comment]
The argument of RANNOR is the seed, check here: http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a000202908.htm

**Comment by xieliaing** [comment]
robertosannazzaro was right on. close the issue.
